# Generated by Django 3.2.6 on 2021-08-21 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddClassWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('imagephoto', models.ImageField(blank=True, upload_to='images/')),
                ('document', models.FileField(blank=True, upload_to='documents/')),
                ('myclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.createclass')),
            ],
        ),
    ]
