# Generated by Django 4.0.5 on 2022-06-16 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_addclasswork_end_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinclass',
            name='student_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.studentregister'),
        ),
    ]
