# Generated by Django 3.2.6 on 2021-08-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_commentinclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkdoneClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfile', models.FileField(blank=True, upload_to='mywork/')),
                ('myclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.addclasswork')),
            ],
        ),
    ]
