# Generated by Django 4.0.5 on 2022-06-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_joinclass_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addclasswork',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.joinclass'),
        ),
        migrations.AlterField(
            model_name='addclasswork',
            name='myclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.createclass'),
        ),
    ]
