# Generated by Django 3.2.6 on 2021-11-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_addclasswork_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='addclasswork',
            name='mytopic',
            field=models.CharField(choices=[('Assignment', 'Assignment'), ('Presentation', 'Presentation'), ('Exam Info', 'Exam Info')], default='Presentation', max_length=20),
        ),
    ]
