# Generated by Django 3.2.9 on 2021-11-16 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_addclasswork_mytopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='addclasswork',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 16, 14, 35, 41, 881726, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addclasswork',
            name='end_date_time',
            field=models.DateTimeField(blank=True, default='2018-11-20T15:58:44.767594-06:00'),
        ),
    ]
